# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'VelibStations' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VelibStations
  pod 'GooglePlaces', '= 3.5.0.0'
  pod 'GoogleMaps', '= 3.5.0.0'
  
  pod 'MaterialComponents/Snackbar'
  
  pod 'SwiftGen', '~> 6.1.0'

  target 'VelibStationsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VelibStationsUITests' do
    # Pods for testing
  end

end
